language: python # => 1

    python: # => 2

      - "3.6"

    services: # => 3

      - postgresql

    env: # => 4

      -DJANGO=2.1.7 DB=postgres

    before_install:
      - export DJANGO_SETTINGS_MODULE=djangotest.settings
      - export PYTHONPATH=$HOME/builds/linneudm/djangotest
      - export PIP_USE_MIRRORS=true
    install: # => 5

      - pip install -r requirements.txt

    before_script: # => 6

      - psql -c "CREATE DATABASE mydb;" -U postgres

    script: # => 7

      - python manage.py test