# Generated by Django 2.1.7 on 2019-03-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190315_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], default='Entrada', max_length=1, verbose_name='Operação'),
        ),
    ]
