# Generated by Django 2.1.7 on 2019-03-16 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_auto_20190315_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Preco Unitário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], default='Entrada', max_length=10, verbose_name='Operação'),
        ),
    ]
